"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import {
  ArrowDownRightIcon,
  ArrowRightIcon,
  ArrowUpRightIcon,
  ArrowUpIcon,
  BanknotesIcon,
  Bars3Icon,
  ChartBarIcon,
  CheckIcon,
  ChevronDownIcon,
  CircleStackIcon,
  CodeBracketIcon,
  CommandLineIcon,
  GlobeAltIcon,
  LockClosedIcon,
  MoonIcon,
  ShieldCheckIcon,
  SignalIcon,
  SunIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

const protocols = ["HTTP", "HTTPS CONNECT", "SOCKS5"];

const proxyProducts = [
  { name: "Shared gateway", status: "Available", description: "Current shared proxy access for straightforward development and testing workflows.", icon: CircleStackIcon, accent: "cyan", tags: ["HTTP", "SOCKS5", "Usage billing"] },
  { name: "ISP", status: "Coming soon", description: "Stable ISP-sourced routing for long-running workflows and verification.", icon: SignalIcon, accent: "violet", tags: ["Planned source", "Location-aware"] },
  { name: "Residential", status: "Coming soon", description: "Residential network access for location-sensitive intelligence workflows.", icon: GlobeAltIcon, accent: "amber", tags: ["Planned source", "Research"] },
  { name: "Mobile", status: "Coming soon", description: "Mobile network access for app, ad and network testing scenarios.", icon: SignalIcon, accent: "blue", tags: ["Planned source", "Testing"] },
] as const;

const faqs = [
  ["What is VornShield?", "VornShield is a proxy access and traffic control plane operated by Vickins Technologies. It gives customers a single place to create an account, access supported proxy credentials, purchase traffic and review usage."],
  ["Which protocols are supported?", "The current shared gateway exposes HTTP, HTTPS CONNECT and SOCKS5 access. The page only lists protocol capabilities currently supported by the backend."],
  ["How does billing work?", "VornShield uses usage-based pricing at $6 USD per GB. Traffic packages and payment confirmation are handled by the authenticated billing flow and Flutterwave checkout."],
  ["Can I target a location?", "Not yet. The current provider returns no public location inventory, so VornShield does not advertise countries, cities, ASNs or latency figures today."],
  ["Can I use VornShield through an API?", "A public developer API is not available in the current implementation. API access is marked as coming soon rather than presenting an endpoint that may not work."],
  ["Do you support sticky or rotating proxies?", "Not currently. The existing shared provider does not enforce sticky sessions, rotation, health checks or failover."],
  ["How do I monitor usage?", "After signing in, the dashboard shows traffic balance, traffic used, payments, usage snapshots and the credentials provisioned for the account."],
  ["What are the acceptable-use rules?", "Use VornShield for legitimate business, development, testing and publicly available data workflows. Customers are responsible for complying with applicable laws and third-party terms."],
] as const;

function Brand({ compact = false }: { compact?: boolean }) {
  return <Link href="/" className="brand" aria-label="VornShield home"><Image src="/v-guard-logo.png" alt="" width={42} height={42} priority={!compact} /><span>VORNSHIELD<small>{compact ? "" : "NETWORK CONTROL"}</small></span></Link>;
}

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <div className={`reveal ${className}`} style={{ "--reveal-delay": `${delay}s` } as React.CSSProperties}>{children}</div>;
}

function ThemeToggle({ theme, onToggle }: { theme: "dark" | "light"; onToggle: () => void }) {
  const nextTheme = theme === "dark" ? "light" : "dark";
  return <button className="theme-toggle" type="button" aria-label="Toggle theme" title={`Switch to ${nextTheme} theme`} onClick={onToggle}>{theme === "dark" ? <MoonIcon /> : <SunIcon />}</button>;
}

function Preloader() {
  return <div className="preloader" role="status" aria-label="Initializing VornShield"><div className="preloader-orbit"><span /><span /><span /></div><Image src="/v-guard-logo.png" alt="" width={58} height={58} priority className="preloader-logo" /><strong>VORNSHIELD</strong><span className="preloader-line" /><small>INITIALIZING NETWORK CONTROL</small></div>;
}

function NetworkLines() {
  return <svg className="network-lines" viewBox="0 0 620 520" aria-hidden="true"><defs><linearGradient id="route" x1="0" x2="1"><stop offset="0" stopColor="#5be7f2" stopOpacity="0" /><stop offset="0.5" stopColor="#5be7f2" /><stop offset="1" stopColor="#8a78ff" stopOpacity="0" /></linearGradient></defs><path d="M32 100 C180 100 220 190 310 232 S470 315 610 285" pathLength="1" /><path d="M-12 365 C130 350 188 260 296 265 S430 190 635 94" pathLength="1" /><path d="M170 -12 C180 100 310 126 310 232 S430 360 470 540" pathLength="1" /><path d="M24 470 C150 430 200 334 296 265 S450 230 610 430" pathLength="1" /><circle cx="310" cy="232" r="7" /><circle cx="310" cy="232" r="19" /><circle cx="170" cy="100" r="4" /><circle cx="470" cy="360" r="4" /></svg>;
}

function NetworkConsole() {
  return <div className="network-visual" aria-label="Illustrative VornShield Network Intelligence console"><div className="visual-grid" /><NetworkLines /><div className="console-orbit orbit-one" /><div className="console-orbit orbit-two" /><div className="intelligence-console"><div className="intel-header"><div><span className="console-label">VORNSHIELD</span><strong>NETWORK INTELLIGENCE</strong></div><span className="console-badge"><i /> ILLUSTRATIVE UI</span></div><div className="intel-map"><div className="map-ring map-ring-one" /><div className="map-ring map-ring-two" /><div className="map-connection connection-a" /><div className="map-connection connection-b" /><div className="map-connection connection-c" /><div className="gateway-core"><span className="core-pulse" /><b>V</b><strong>GATEWAY</strong><small>ONLINE</small></div><div className="intel-node node-a"><i /><span>SOURCE A</span><strong>Shared</strong><small>Available</small></div><div className="intel-node node-b"><i /><span>SOURCE B</span><strong>HTTP/S</strong><small>Supported</small></div><div className="intel-node node-c"><i /><span>SOURCE C</span><strong>SOCKS5</strong><small>Supported</small></div></div><div className="intel-stats"><div><span>ROUTE</span><strong>Shared gateway</strong></div><div><span>PROTOCOL</span><strong>HTTP / SOCKS5</strong></div><div><span>LATENCY</span><strong>Not exposed</strong></div></div></div><div className="floating-stat stat-top"><span className="stat-pulse" /><div><small>ACCESS LAYER</small><strong>Authenticated</strong></div></div><div className="floating-stat stat-bottom"><span className="tiny-icon"><ShieldCheckIcon /></span><div><small>TRAFFIC STATE</small><strong>Usage-based</strong></div></div><div className="floating-stat stat-side"><span className="tiny-icon"><SignalIcon /></span><div><small>SESSION ENGINE</small><strong>Planned</strong></div></div></div>;
}

function DashboardPreview() {
  return <div className="dashboard-frame" aria-label="Illustrative VornShield dashboard preview"><div className="dash-topbar"><span className="window-dots"><i /><i /><i /></span><span className="dash-url">app.vornshield.com / dashboard</span><span className="dash-avatar">A</span></div><div className="dash-layout"><aside className="dash-sidebar"><Brand compact /><span className="dash-section-label">WORKSPACE</span><span className="dash-link active">Overview</span><span className="dash-link">Traffic</span><span className="dash-link">Proxy access</span><span className="dash-link">Billing</span><span className="dash-section-label">ACCOUNT</span><span className="dash-link">API keys</span></aside><div className="dash-main"><div className="dash-heading"><div><span className="micro-label">ILLUSTRATIVE PREVIEW</span><h3>Control center</h3></div><span className="healthy"><i /> Account active</span></div><div className="dash-metrics"><div><span>TRAFFIC BALANCE</span><strong>— GB</strong><small>Backend value</small></div><div><span>TRAFFIC USED</span><strong>— GB</strong><small>Backend value</small></div><div><span>PROXY ACCESS</span><strong>Ready</strong><small>HTTP · SOCKS5</small></div></div><div className="dash-panels"><div className="dash-panel"><div className="panel-title"><span>Usage activity</span><small>Recent snapshots</small></div><div className="chart"><i /><i /><i /><i /><i /><i /><i /><b /></div></div><div className="dash-panel credential-panel"><div className="panel-title"><span>Credentials</span><small>Provisioned access</small></div><div><span>HTTP</span><b>Available after sign in</b></div><div><span>SOCKS5</span><b>Available after sign in</b></div></div></div></div></div></div>;
}

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [traffic, setTraffic] = useState(10);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [scrolled, setScrolled] = useState(false);
  const [showBackToTop, setShowBackToTop] = useState(false);
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [booting, setBooting] = useState(true);
  const sidebarCloseRef = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    const storedTheme = window.localStorage.getItem("vornshield-theme");
    const nextTheme = storedTheme === "light" ? "light" : "dark";
    setTheme(nextTheme);
    document.documentElement.dataset.theme = nextTheme;
    const onScroll = () => { setScrolled(window.scrollY > 16); setShowBackToTop(window.scrollY > 480); };
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setMenuOpen(false); };
    window.addEventListener("keydown", onKeyDown);
    const timer = window.setTimeout(() => setBooting(false), 850);
    return () => { window.removeEventListener("scroll", onScroll); window.removeEventListener("keydown", onKeyDown); window.clearTimeout(timer); };
  }, []);
  useEffect(() => { document.body.classList.toggle("no-scroll", menuOpen); return () => document.body.classList.remove("no-scroll"); }, [menuOpen]);
  useEffect(() => { if (menuOpen) window.setTimeout(() => sidebarCloseRef.current?.focus(), 0); }, [menuOpen]);
  const closeMenu = () => setMenuOpen(false);
  const toggleTheme = () => { const nextTheme = theme === "dark" ? "light" : "dark"; setTheme(nextTheme); document.documentElement.dataset.theme = nextTheme; window.localStorage.setItem("vornshield-theme", nextTheme); };

  return <main className="vornshield-site">
    {booting && <Preloader />}
    <header className={`site-header ${scrolled ? "is-scrolled" : ""}`}><div className="site-nav"><Brand /><nav className="desktop-nav" aria-label="Primary navigation"><a href="#proxy-types">Proxies</a><a href="#locations">Locations</a><a href="#pricing">Pricing</a><a href="#developer-api">API</a><a href="#why-vornshield">Features</a><a href="#faq">Resources</a></nav><div className="nav-actions"><ThemeToggle theme={theme} onToggle={toggleTheme} /><Link href="/login" className="nav-login">Sign in</Link><Link href="/login" className="button button-small">Get started <ArrowRightIcon /></Link><button className="menu-toggle" type="button" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <XMarkIcon /> : <Bars3Icon />}</button></div></div></header>
    {menuOpen && <><div className="mobile-sidebar-backdrop is-open" onClick={closeMenu} /><aside className="mobile-sidebar is-open" aria-label="Mobile navigation"><div className="mobile-sidebar-head"><Brand compact /><button ref={sidebarCloseRef} type="button" className="sidebar-close" aria-label="Close navigation" onClick={closeMenu}><XMarkIcon /></button></div><nav><a href="#proxy-types" onClick={closeMenu}>Proxies</a><a href="#locations" onClick={closeMenu}>Locations</a><a href="#pricing" onClick={closeMenu}>Pricing</a><a href="#developer-api" onClick={closeMenu}>API</a><a href="#why-vornshield" onClick={closeMenu}>Features</a><a href="#faq" onClick={closeMenu}>Resources</a></nav><div className="mobile-sidebar-actions"><Link href="/login" onClick={closeMenu}>Sign in</Link><Link href="/login" className="button" onClick={closeMenu}>Get started <ArrowRightIcon /></Link></div><span className="sidebar-foot">VORNSHIELD / NETWORK CONTROL</span></aside></>}

    <section className="hero" id="top"><div className="hero-backdrop" /><div className="hero-glow hero-glow-one" /><div className="hero-glow hero-glow-two" /><div className="container hero-layout"><div className="hero-copy"><Reveal><div className="eyebrow"><span className="eyebrow-line" /> NETWORK INFRASTRUCTURE / 01</div></Reveal><Reveal delay={0.05}><h1>Proxy infrastructure.<br /><em>Built for scale.</em></h1></Reveal><Reveal delay={0.1}><p className="hero-lede">Fast, flexible proxy access for automation, testing and modern data workflows — with the account controls and usage visibility to keep your traffic clear.</p></Reveal><Reveal delay={0.15}><div className="hero-actions"><Link href="/login" className="button">Get started <ArrowRightIcon /></Link><a href="#proxy-types" className="text-link">Explore proxies <ArrowDownRightIcon /></a></div></Reveal><Reveal delay={0.2}><div className="hero-note"><CheckIcon /> Current access: HTTP · HTTPS CONNECT · SOCKS5 <span>·</span> $6 / GB</div></Reveal></div><Reveal delay={0.12} className="hero-visual"><NetworkConsole /></Reveal></div><div className="container hero-foot"><span>OPERATED BY VICKINS TECHNOLOGIES</span><span className="hero-foot-rule" /><span>ACCESS · TRAFFIC · CONTROL</span></div></section>

    <section className="capability-strip" aria-label="Current VornShield capabilities"><div className="container capability-inner"><span className="strip-label">CURRENTLY SUPPORTED</span>{protocols.map((protocol) => <span className="capability" key={protocol}><i /><b>{protocol}</b></span>)}<span className="capability"><i /><b>Usage billing</b></span><span className="capability-muted">Location targeting — coming soon</span></div></section>

    <section className="section intro-section"><div className="container intro-grid"><Reveal><p className="section-kicker">A control plane for proxy access</p><h2>Move traffic with a clearer point of control.</h2></Reveal><Reveal delay={0.1}><p className="section-copy">VornShield brings account access, credentials, traffic purchases and usage snapshots into one focused workspace. Start with the infrastructure available today, then add network sources as your requirements grow.</p><Link href="/login" className="text-link">Open your workspace <ArrowRightIcon /></Link></Reveal></div></section>

    <section className="section products-section" id="proxy-types"><div className="container"><Reveal><div className="section-heading"><div><p className="section-kicker">Choose your network</p><h2>One gateway.<br /><span>Clear options.</span></h2></div><p className="section-copy">Every source is shown with its actual availability. No invented inventory, locations or performance claims.</p></div></Reveal><div className="product-grid">{proxyProducts.map((product, index) => { const Icon = product.icon; return <Reveal key={product.name} delay={index * 0.05}><article className={`product-card accent-${product.accent} ${product.status !== "Available" ? "is-soon" : ""}`}><div className="product-top"><span className="product-icon"><Icon /></span><span className={`availability ${product.status === "Available" ? "available" : "soon"}`}><i /> {product.status}</span></div><h3>{product.name}</h3><p>{product.description}</p><div className="tag-row">{product.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span className="product-arrow">{product.status === "Available" ? "Use this source" : "Planned source"} <ArrowRightIcon /></span></article></Reveal>; })}</div></div></section>

    <section className="section architecture-section"><div className="container architecture-grid"><Reveal className="architecture-copy"><p className="section-kicker">The VornShield model</p><h2>One gateway.<br /><span>Multiple IP sources.</span></h2><p className="section-copy">VornShield provides one simple interface for managing supported proxy sources. The gateway abstracts the underlying infrastructure without hiding what is actually available.</p><div className="architecture-list"><span><b>01</b> Authenticate once</span><span><b>02</b> Choose a supported source</span><span><b>03</b> Track traffic from the workspace</span></div></Reveal><Reveal delay={0.1}><div className="architecture-visual"><div className="architecture-node customer"><small>YOUR WORKFLOW</small><strong>Customer</strong></div><div className="flow-line"><i /><i /><i /></div><div className="architecture-node gateway"><span className="node-mark">V</span><small>CONTROL PLANE</small><strong>VornShield</strong><em>Unified gateway</em></div><div className="source-stack"><div className="source-node active"><span>01</span><b>Shared gateway</b><small>HTTP · SOCKS5</small><em>Available</em></div><div className="source-node"><span>02</span><b>ISP source</b><small>Location-aware</small><em>Coming soon</em></div><div className="source-node"><span>03</span><b>Residential / Mobile</b><small>Provider adapters</small><em>Coming soon</em></div></div></div></Reveal></div></section>

    <section className="section location-section" id="locations"><div className="container location-panel"><div className="location-copy"><Reveal><p className="section-kicker">Location targeting</p><h2>Target the network.<br /><span>Not just the country.</span></h2><p className="section-copy">Location, region, city and ISP targeting are designed into the gateway model. They are not advertised until a real inventory source is connected.</p><div className="location-unavailable"><LockClosedIcon /><div><strong>Public inventory not available yet</strong><span>The current provider returns no location data.</span></div></div></Reveal></div><Reveal delay={0.1}><div className="location-console"><div className="location-console-top"><span>ROUTING FILTERS</span><b>NOT CONFIGURED</b></div>{["Country", "Region", "City", "ISP / ASN"].map((label) => <div className="location-field" key={label}><span>{label}</span><strong>Unavailable</strong><ChevronDownIcon /></div>)}<small>Filters will appear when verified network inventory is connected.</small></div></Reveal></div></section>

    <section className="section pricing-section" id="pricing"><div className="container pricing-grid"><Reveal><p className="section-kicker">Usage-based pricing</p><h2>Simple pricing.<br /><span>No guesswork.</span></h2><p className="section-copy">Start with the traffic you need. Backend billing remains the source of truth for every purchase and balance.</p><div className="price-lockup"><strong>$6</strong><span>/ GB<br /><small>USD</small></span></div><div className="price-points"><span><CheckIcon /> Pay for the traffic you use</span><span><CheckIcon /> Transparent usage tracking</span><span><CheckIcon /> Secure checkout confirmation</span></div><Link href="/login" className="button">Start using VornShield <ArrowRightIcon /></Link></Reveal><Reveal delay={0.1}><div className="calculator-card"><div className="calculator-top"><div><span className="micro-label">TRAFFIC CALCULATOR</span><h3>Estimate your starting spend</h3></div><BanknotesIcon /></div><div className="traffic-options">{[1, 5, 10, 25, 50, 100].map((value) => <button key={value} className={traffic === value ? "selected" : ""} type="button" onClick={() => setTraffic(value)}>{value} GB</button>)}</div><label htmlFor="traffic-range">Traffic required <strong>{traffic} GB</strong></label><input id="traffic-range" type="range" min="1" max="100" step="1" value={traffic} onChange={(event) => setTraffic(Number(event.target.value))} /><div className="estimate"><span>Estimated cost</span><strong>${traffic * 6}</strong><small>{traffic} GB × $6 USD</small></div><small className="calculator-note">Estimate only. Final billing is validated by the backend during checkout.</small></div></Reveal></div></section>

    <section className="section process-section" id="how-it-works"><div className="container"><Reveal><div className="section-heading"><div><p className="section-kicker">How it works</p><h2>From account to<br /><span>active access.</span></h2></div><p className="section-copy">A short path from sign-up to the credentials and traffic state you can actually use.</p></div></Reveal><div className="process-flow">{[["01", "Create your account", "Register and open your VornShield workspace."], ["02", "Choose your traffic", "Review available plans and select a traffic package."], ["03", "Connect and monitor", "Use supported credentials and review usage snapshots."]].map(([number, title, copy], index) => <Reveal key={number} delay={index * 0.08}><article className="process-step"><span className="step-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div>{index < 2 && <ArrowRightIcon className="step-arrow" />}</article></Reveal>)}</div><div className="flow-caption"><span>ACCOUNT</span><i /><span>TRAFFIC</span><i /><span>CONNECTION</span><i /><span>INTERNET</span></div></div></section>

    <section className="section api-section" id="developer-api"><div className="container api-panel"><div className="api-copy"><Reveal><span className="api-mark"><CodeBracketIcon /></span><p className="section-kicker">Developer surface</p><h2>Built for developers.<br /><span>API — coming soon.</span></h2><p className="section-copy">A unified programmatic interface is on the roadmap. When it is available, it will expose only the operations supported by the underlying gateway.</p><span className="coming-badge"><i /> In development</span></Reveal></div><Reveal delay={0.1}><div className="code-panel"><div className="code-top"><span><i /><i /><i /></span><small>future request surface</small><span className="code-lock"><LockClosedIcon /> Not live</span></div><pre><code><span className="code-muted">// Developer API</span>{"\n"}<span className="code-key">STATUS</span> <span className="code-string">"COMING_SOON"</span>{"\n"}<span className="code-key">AUTH</span>   <span className="code-string">"secure_api_auth"</span>{"\n"}<span className="code-key">SCOPE</span>  <span className="code-string">"proxy_access, usage"</span></code></pre><div className="code-foot"><CommandLineIcon /> Endpoint documentation will be published when the API is implemented.</div></div></Reveal></div></section>

    <section className="section session-section"><div className="container session-grid"><Reveal><p className="section-kicker">Session control</p><h2>Control every<br /><span>connection.</span></h2><p className="section-copy">Persistent and rotating session controls need a real session engine behind them. VornShield keeps those controls visible as planned capabilities until they are ready.</p><div className="session-tabs"><span className="active">STICKY <small>Planned</small></span><span>ROTATING <small>Planned</small></span></div></Reveal><Reveal delay={0.1}><div className="session-visual"><div className="timeline-line" /><div className="timeline-step"><span>01</span><strong>IP A</strong><small>Session start</small></div><div className="timeline-step"><span>02</span><strong>IP A</strong><small>Sticky window</small></div><div className="timeline-step muted"><span>03</span><strong>IP B</strong><small>Rotation engine</small></div><div className="timeline-step muted"><span>04</span><strong>IP C</strong><small>Not configured</small></div></div></Reveal></div></section>

    <section className="section dashboard-section" id="dashboard"><div className="container dashboard-grid"><Reveal><div className="dashboard-copy"><p className="section-kicker">Inside the workspace</p><h2>See the state of your account at a glance.</h2><p className="section-copy">The authenticated dashboard brings together traffic balance, plans, payments, usage snapshots and supported proxy credentials.</p><div className="dashboard-list"><span><CheckIcon /> Traffic balance and usage</span><span><CheckIcon /> HTTP and SOCKS5 credentials</span><span><CheckIcon /> Payment history</span><span><CheckIcon /> Active account state</span></div><Link href="/login" className="text-link">Open the dashboard <ArrowRightIcon /></Link></div></Reveal><Reveal delay={0.1}><DashboardPreview /></Reveal></div></section>

    <section className="section why-section" id="why-vornshield"><div className="container"><Reveal><div className="section-heading"><div><p className="section-kicker">Why VornShield</p><h2>Infrastructure with<br /><span>fewer unknowns.</span></h2></div><p className="section-copy">Clear capability boundaries, authenticated access and usage visibility form the foundation.</p></div></Reveal><div className="why-grid">{[[ShieldCheckIcon, "Authenticated access", "Credentials are provisioned behind an account-backed control plane."], [BanknotesIcon, "Usage visibility", "Track traffic used, traffic remaining and confirmed purchases."], [SignalIcon, "Supported protocols", "Connect through the current HTTP, HTTPS CONNECT and SOCKS5 gateway."], [GlobeAltIcon, "Global targeting", "Add verified locations as real network inventory becomes available."], [CodeBracketIcon, "Developer ready", "A documented API surface is planned for programmatic workflows."], [LockClosedIcon, "Responsible controls", "Monitoring, rate limits and abuse controls support legitimate use."]].map(([Icon, title, copy], index) => { const FeatureIcon = Icon as typeof ShieldCheckIcon; return <Reveal key={title as string} delay={index * 0.04}><article className="why-card"><FeatureIcon /><h3>{title as string}</h3><p>{copy as string}</p></article></Reveal>; })}</div></div></section>

    <section className="section use-cases-section"><div className="container"><Reveal><div className="section-heading"><div><p className="section-kicker">Built for real workflows</p><h2>Useful by design.<br /><span>Responsible by default.</span></h2></div><p className="section-copy">VornShield is intended for legitimate business, development, testing and publicly available data workflows.</p></div></Reveal><div className="use-case-row">{[["Web intelligence", "Collect publicly available data at a measured scale."], ["SEO & market research", "Monitor search results and market signals across workflows."], ["QA & testing", "Test applications across supported network environments."], ["Ad verification", "Validate location-sensitive campaigns when targeting is available."], ["E-commerce", "Monitor product availability and pricing across markets."], ["Automation", "Build proxy-aware workflows into your applications."]].map(([title, copy]) => <article className="use-case" key={title}><span>{title}</span><p>{copy}</p><ArrowUpRightIcon /></article>)}</div></div></section>

    <section className="section health-section"><div className="container health-panel"><div className="health-copy"><Reveal><p className="section-kicker">Network health</p><h2>Your traffic deserves<br /><span>clear infrastructure.</span></h2><p className="section-copy">Live health metrics are not exposed by the current provider. This conceptual view shows how VornShield will surface gateway state as the network grows.</p></Reveal></div><Reveal delay={0.1}><div className="health-grid"><div><span className="health-icon"><SignalIcon /></span><small>GATEWAY</small><strong>Connected</strong><em>Control plane ready</em></div><div><span className="health-icon"><CircleStackIcon /></span><small>POOL</small><strong>Shared source</strong><em>Current provider</em></div><div><span className="health-icon"><ArrowRightIcon /></span><small>ROUTE</small><strong>Active</strong><em>HTTP / SOCKS5</em></div><div><span className="health-icon"><ChartBarIcon /></span><small>TRAFFIC</small><strong>Monitored</strong><em>Dashboard snapshots</em></div></div></Reveal></div></section>

    <section className="section faq-section" id="faq"><div className="container faq-grid"><Reveal><p className="section-kicker">Resources</p><h2>Good questions<br /><span>deserve clear answers.</span></h2><p className="section-copy">Short answers to the things that matter before you route production traffic.</p><Link href="/policy" className="text-link">Read acceptable use <ArrowRightIcon /></Link></Reveal><Reveal delay={0.1}><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={question}><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{question}</span><ChevronDownIcon /></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></Reveal></div></section>

    <section className="final-cta"><div className="container final-cta-inner"><Reveal><p className="section-kicker">Ready when you are</p><h2>Build your next workflow<br /><span>on better infrastructure.</span></h2><p>Start with the traffic you need. Scale when the network is ready for more.</p><div className="hero-actions"><Link href="/login" className="button">Get started <ArrowRightIcon /></Link><a href="#proxy-types" className="button button-secondary">Explore proxies</a></div></Reveal><div className="cta-mark"><NetworkLines /><span>V</span></div></div></section>
    <button className={`back-to-top ${showBackToTop ? "is-visible" : ""}`} type="button" aria-label="Back to top" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><ArrowUpIcon /></button>

    <footer className="site-footer"><div className="container footer-main"><div className="footer-brand"><Brand /><p>Proxy infrastructure for modern applications, automation and data workflows.</p><span>Powered by <a href="https://vickinstechnologies.com/" target="_blank" rel="noreferrer">Vickins Technologies</a></span></div><div className="footer-column"><strong>Product</strong><a href="#proxy-types">Shared gateway</a><a href="#proxy-types">ISP — coming soon</a><a href="#pricing">Pricing</a><a href="#locations">Locations</a></div><div className="footer-column"><strong>Developers</strong><a href="#developer-api">API — coming soon</a><a href="#dashboard">Dashboard</a><a href="#faq">FAQ</a><a href="mailto:support@vickinstechnologies.com">Support</a></div><div className="footer-column"><strong>Company</strong><a href="https://vickinstechnologies.com/" target="_blank" rel="noreferrer">About Vickins</a><a href="mailto:hello@vickinstechnologies.com">Contact</a><Link href="/terms">Terms</Link><Link href="/policy">Acceptable use</Link></div></div><div className="container footer-bottom"><span>© 2026 VornShield. All rights reserved.</span><span>VORNSHIELD / NETWORK CONTROL</span></div></footer>
  </main>;
}
