"use client";

import { useEffect, useState } from "react";
import { ArrowTopRightOnSquareIcon, CreditCardIcon, ShieldCheckIcon } from "@heroicons/react/24/outline";
import { AppShell } from "../../components/dashboard/DashboardShell";
import { createCheckout, loadDashboard } from "../../lib/api";
import type { DashboardData, PaymentIntent, ProxyPlan } from "../../lib/types";

function money(plan: ProxyPlan) { return `${plan.currency} ${(plan.priceMinorUnits / 100).toLocaleString(undefined, { maximumFractionDigits: 2 })}`; }
function formatGB(value: number) { return `${value.toFixed(2)} GB`; }
export default function BillingPage() {
  const [data, setData] = useState<DashboardData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busyPlan, setBusyPlan] = useState<string | null>(null); const [checkout, setCheckout] = useState<PaymentIntent | null>(null);
  async function refresh() { setLoading(true); setError(null); try { setData(await loadDashboard()); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load billing data"); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  async function handleCheckout(planId: string) { setBusyPlan(planId); setError(null); try { const response = await createCheckout(planId); setCheckout(response.data); window.location.href = response.data.flutterwaveLink; } catch (err) { setError(err instanceof Error ? err.message : "Checkout failed"); } finally { setBusyPlan(null); } }
  if (loading) return <AppShell onRefresh={refresh} refreshing><div className="skeleton-page"><div className="skeleton-line wide" /><div className="skeleton-card tall" /></div></AppShell>;
  return <AppShell userName={data?.user.displayName || data?.user.email} role={data?.user.role} onRefresh={refresh} refreshing={loading}><div className="dashboard-stack"><section className="welcome-row"><div><p className="eyebrow-blue">BILLING CENTER</p><h1>Buy proxy traffic</h1><p className="subtle">The canonical V-Guard rate is $6 USD per GB.</p></div><div className="balance-chip"><span>TRAFFIC BALANCE</span><strong>{data ? formatGB(data.stats.trafficBalanceGB) : "0.00 GB"}</strong></div></section>{error && <div className="inline-error">{error}</div>}{checkout && <div className="inline-success">Checkout created for {checkout.reference}. Redirecting to Flutterwave…</div>}
      <section className="billing-summary"><article className="metric-card"><div className="metric-top"><span className="metric-label">Remaining</span><span className="metric-icon"><ShieldCheckIcon /></span></div><strong>{data ? formatGB(data.stats.trafficBalanceGB) : "0.00 GB"}</strong><small>Traffic available</small></article><article className="metric-card"><div className="metric-top"><span className="metric-label">Used</span><span className="metric-icon"><CreditCardIcon /></span></div><strong>{data ? formatGB(data.stats.trafficUsedGB) : "0.00 GB"}</strong><small>{data?.stats.usagePercent.toFixed(1) ?? "0.0"}% of total</small></article><div className="billing-note"><ShieldCheckIcon /><span><strong>Secure checkout</strong><small>Traffic is added only after backend webhook confirmation.</small></span></div></section>
      <section className="panel-card"><div className="panel-heading"><div><p className="eyebrow-blue">TRAFFIC PACKAGES</p><h2>Select a plan</h2></div><span className="panel-meta">$6 USD / GB</span></div><div className="plan-grid billing-plans">{(data?.plans || []).map((plan) => <article className={`plan-card ${plan.isPopular ? "popular" : ""}`} key={plan.id}>{plan.isPopular && <span className="popular-label">POPULAR</span>}<span className="plan-name">{plan.name}</span><strong>{money(plan)}</strong><span className="plan-credits">{formatGB(plan.trafficGB)}</span><p>{plan.description}</p><button className="primary-button full" onClick={() => void handleCheckout(plan.id)} disabled={busyPlan === plan.id}>{busyPlan === plan.id ? "Opening checkout…" : <>Pay with Flutterwave <ArrowTopRightOnSquareIcon /></>}</button></article>)}</div>{!data?.plans.length && <div className="empty-inline compact"><CreditCardIcon /><span>No active plans available.</span></div>}</section>
      <section className="panel-card"><div className="panel-heading"><div><p className="eyebrow-blue">PAYMENT HISTORY</p><h2>Recent purchases</h2></div><span className="panel-meta">Backend-confirmed activity</span></div><div className="billing-table"><div className="billing-table-head"><span>Reference</span><span>Traffic</span><span>Amount</span><span>Status</span></div>{(data?.payments || []).length ? data?.payments.map((payment) => <div className="billing-table-row" key={payment.id}><span>{payment.reference}</span><b>{formatGB(payment.trafficGB)}</b><span>{payment.currency} {(payment.amountMinorUnits / 100).toLocaleString()}</span><span className="status-tag">{payment.status}</span></div>) : <div className="empty-inline compact"><CreditCardIcon /><span>No recent purchases.</span></div>}</div></section>
    </div></AppShell>;
}
