"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { ArrowPathIcon, ArrowRightOnRectangleIcon, Bars3Icon, BellIcon, BellAlertIcon, ChartBarIcon, CheckIcon, ChevronDownIcon, ClipboardDocumentIcon, CreditCardIcon, CubeIcon, DocumentTextIcon, GlobeAltIcon, HomeIcon, KeyIcon, LockClosedIcon, MoonIcon, QuestionMarkCircleIcon, RectangleStackIcon, ShieldCheckIcon, SignalIcon, SunIcon, UsersIcon, UserCircleIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { clearSession, readSession } from "../../lib/session";
import type { DashboardData, ProxySyncResult } from "../../lib/types";

type Props = { data: DashboardData | null; loading: boolean; error: string | null; onRefresh: () => void; onSyncProxy: () => Promise<void>; syncingProxy: boolean; syncResult: ProxySyncResult | null; providerConnected?: boolean };

function safeNumber(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
function formatGB(value: number | null | undefined) { return `${safeNumber(value).toFixed(2)} GB`; }
function formatPercent(value: number | null | undefined) { return `${safeNumber(value).toFixed(1)}%`; }
function money(amount: number, currency: string) { return `${currency} ${(amount / 100).toLocaleString(undefined, { maximumFractionDigits: 2 })}`; }

type NavItem = { label: string; href?: string; icon: React.ElementType; unavailable?: boolean };
type NavGroup = { label: string; items: NavItem[] };

const navGroups: NavGroup[] = [
  { label: "Workspace", items: [{ label: "Overview", href: "/dashboard", icon: HomeIcon }, { label: "Proxy network", href: "/proxies", icon: SignalIcon }, { label: "Locations", href: "/locations", icon: GlobeAltIcon }, { label: "Sessions", href: "/sessions", icon: UsersIcon }, { label: "Usage", href: "/usage", icon: ChartBarIcon }] },
  { label: "Management", items: [{ label: "Billing", href: "/billing", icon: CreditCardIcon }, { label: "API", href: "/api", icon: DocumentTextIcon }, { label: "Credentials", href: "/credentials", icon: KeyIcon }] },
  { label: "System", items: [{ label: "Notifications", href: "/notifications", icon: BellAlertIcon }, { label: "Settings", href: "/settings", icon: LockClosedIcon }, { label: "Profile", href: "/profile", icon: UserCircleIcon }, { label: "Support", href: "/support", icon: QuestionMarkCircleIcon }] },
];

function GlobePlaceholderIcon(props: React.ComponentProps<"svg">) { return <SignalIcon {...props} />; }

export function AppShell({ children, userName, role, onRefresh, refreshing, onSignOut }: { children: React.ReactNode; userName?: string; role?: string; onRefresh?: () => void; refreshing?: boolean; onSignOut?: () => void }) {
  const router = useRouter();
  const pathname = usePathname();
  const [collapsed, setCollapsed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [accountOpen, setAccountOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const closeRef = useRef<HTMLButtonElement>(null);
  const displayName = userName || "VornShield user";
  const title = pathname === "/dashboard" ? "Overview" : pathname === "/proxies" || pathname.startsWith("/proxies/") ? "Proxy network" : pathname.slice(1).split("/")[0]?.replace(/-/g, " ") || "Overview";

  useEffect(() => {
    const stored = window.localStorage.getItem("vornshield-theme");
    const next = stored === "light" ? "light" : "dark";
    setTheme(next);
    document.documentElement.dataset.theme = next;
  }, []);
  useEffect(() => { document.body.classList.toggle("no-scroll", mobileOpen); if (mobileOpen) window.setTimeout(() => closeRef.current?.focus(), 0); return () => document.body.classList.remove("no-scroll"); }, [mobileOpen]);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") { setMobileOpen(false); setAccountOpen(false); setNotificationsOpen(false); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, []);

  function toggleTheme() { const next = theme === "dark" ? "light" : "dark"; setTheme(next); document.documentElement.dataset.theme = next; window.localStorage.setItem("vornshield-theme", next); }
  function signOut() { clearSession(); onSignOut?.(); router.replace("/login"); }
  function isActive(href?: string) { return Boolean(href && href.startsWith(pathname)); }

  return <div className={`admin-app ${collapsed ? "sidebar-collapsed" : ""}`}>
    {mobileOpen && <button className="drawer-overlay" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}
    <aside className={`admin-sidebar ${mobileOpen ? "drawer-open" : ""}`} aria-label="VornShield control panel navigation"><div className="sidebar-brand"><Link href="/dashboard" className="sidebar-brand-link" onClick={() => setMobileOpen(false)}><Image className="brand-logo" src="/v-guard-logo.png" alt="" width={36} height={36} priority /><span className="brand-copy"><strong>VORNSHIELD</strong><small>NETWORK CONTROL</small></span></Link><button ref={closeRef} className="sidebar-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><XMarkIcon /></button></div><div className="sidebar-rule" />
      {navGroups.map((group) => <div className="sidebar-group" key={group.label}><p className="sidebar-label">{group.label}</p><nav className="sidebar-nav" aria-label={group.label}>{group.items.map((item) => { const { label, icon: Icon, unavailable, href } = item; return unavailable || !href ? <span key={label} className="sidebar-link disabled" title={`${label} is coming soon`} aria-label={`${label} coming soon`}><Icon /><span>{label}</span><em>soon</em></span> : <Link key={label} href={href} className={`sidebar-link ${isActive(href) ? "active" : ""}`} title={collapsed ? label : undefined} onClick={() => setMobileOpen(false)}><Icon /><span>{label}</span></Link>; })}</nav></div>)}
      <div className="sidebar-bottom"><div className="sidebar-user"><span className="avatar">{displayName.slice(0, 1).toUpperCase()}</span><span className="sidebar-user-copy"><strong>{displayName}</strong><small>{role === "admin" ? "Administrator" : "Authenticated account"}</small></span><ChevronDownIcon /></div><button className="sidebar-signout" onClick={signOut} title="Sign out"><ArrowRightOnRectangleIcon /><span>Sign out</span></button></div>
    </aside>
    <div className="admin-main"><header className="admin-header"><div className="header-left"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Bars3Icon /></button><button className="icon-button desktop-collapse" onClick={() => setCollapsed(!collapsed)} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}><Bars3Icon /></button><div><p className="header-kicker">VORNSHIELD / SECURE CONSOLE</p><p className="header-page">{title}</p></div></div><div className="header-actions"><div className="header-popover-wrap"><button className="icon-button" onClick={() => { setNotificationsOpen(!notificationsOpen); setAccountOpen(false); }} aria-label="Notifications" aria-expanded={notificationsOpen}><BellIcon /><i className="notification-dot" /></button>{notificationsOpen && <div className="header-popover notification-popover"><div><strong>Notifications</strong><small>System and account events</small></div><div className="popover-empty"><BellIcon /><span>No new notifications</span></div></div>}</div><button className="icon-button" onClick={toggleTheme} aria-label="Toggle theme" title={`Switch to ${theme === "dark" ? "light" : "dark"} theme`}>{theme === "dark" ? <MoonIcon /> : <SunIcon />}</button>{onRefresh && <button className="header-refresh" onClick={onRefresh} disabled={refreshing}><ArrowPathIcon className={refreshing ? "spin" : ""} /><span>{refreshing ? "Refreshing" : "Refresh"}</span></button>}<div className="header-popover-wrap"><button className="header-profile" onClick={() => { setAccountOpen(!accountOpen); setNotificationsOpen(false); }} aria-expanded={accountOpen}><span className="avatar">{displayName.slice(0, 1).toUpperCase()}</span><span><strong>{displayName}</strong><small>{role === "admin" ? "Administrator" : "Account"}</small></span><ChevronDownIcon /></button>{accountOpen && <div className="header-popover account-popover"><div className="account-summary"><span className="avatar large">{displayName.slice(0, 1).toUpperCase()}</span><span><strong>{displayName}</strong><small>{role === "admin" ? "Administrator" : "Authenticated account"}</small></span></div><Link href="/dashboard" onClick={() => setAccountOpen(false)}>Overview</Link><Link href="/billing" onClick={() => setAccountOpen(false)}>Billing</Link><button onClick={signOut}><ArrowRightOnRectangleIcon /> Sign out</button></div>}</div><button className="signout-desktop" onClick={signOut} aria-label="Sign out"><ArrowRightOnRectangleIcon /></button></div></header><main className="admin-content">{children}</main></div>
  </div>;
}

function CopyCredential({ label, value }: { label: string; value: string }) { const [copied, setCopied] = useState(false); async function copy() { await navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } return <div className="credential-row"><div><span className="credential-label">{label}</span><code>{value}</code></div><button className="copy-button" onClick={() => void copy()} aria-label={`Copy ${label} credential`}>{copied ? <><CheckIcon /> Copied</> : <><ClipboardDocumentIcon /> Copy</>}</button></div>; }

export default function DashboardShell({ data, loading, error, onRefresh, onSyncProxy, syncingProxy, syncResult, providerConnected = false }: Props) {
  const router = useRouter();
  const [sessionReady, setSessionReady] = useState(false);
  const [hasSession, setHasSession] = useState(true);
  useEffect(() => { setSessionReady(true); const session = readSession(); setHasSession(Boolean(session)); if (!session) router.replace("/login"); }, [router]);
  if (!sessionReady || !hasSession) return <div className="auth-redirect"><div className="preloader-orbit small-orbit" /><span>Restoring secure session…</span></div>;
  const userName = data?.user.displayName || data?.user.email || "Account";
  if (loading) return <AppShell userName={userName}><div className="skeleton-page"><div className="skeleton-line wide" /><div className="metric-grid">{[1, 2, 3, 4].map((item) => <div className="skeleton-card" key={item} />)}</div><div className="skeleton-card tall" /></div></AppShell>;
  if (error || !data) return <AppShell userName={userName} onRefresh={onRefresh}><div className="state-card error-state"><div className="state-icon"><ShieldCheckIcon /></div><p className="eyebrow-blue">SECURE CONSOLE</p><h1>Something went wrong.</h1><p>VornShield couldn’t load this account data. Try again.</p><button className="primary-button" onClick={onRefresh}>Try again</button></div></AppShell>;
  const plans = data.plans || [], payments = data.payments || [], usage = data.usage || [], usageSeries = usage.slice(0, 10);
  const stats = [{ label: "Traffic used", value: formatGB(data.stats.trafficUsedGB), note: `${formatPercent(data.stats.usagePercent)} of total`, icon: ChartBarIcon }, { label: "Available balance", value: formatGB(data.stats.trafficBalanceGB), note: "GB available", icon: ShieldCheckIcon }, { label: "Active sessions", value: "—", note: "Provider data unavailable", icon: UsersIcon }, { label: "Healthy endpoints", value: "—", note: "Provider data unavailable", icon: SignalIcon }];
  return <AppShell userName={userName} role={data.user.role} onRefresh={onRefresh} refreshing={loading} onSignOut={() => clearSession()}><div className="dashboard-stack"><section className="welcome-row"><div><p className="eyebrow-blue">ACCOUNT OVERVIEW</p><h1>Good to see you, {userName.split(" ")[0]}</h1><p className="subtle">Monitor your proxy infrastructure and traffic from one place.</p></div><div className="live-pill"><span /> {data.user.active ? "Account active" : "Account inactive"}</div></section>
    <section className="metric-grid">{stats.map(({ label, value, note, icon: Icon }) => <article className="metric-card" key={label}><div className="metric-top"><span className="metric-label">{label}</span><span className="metric-icon"><Icon /></span></div><strong>{value}</strong><small>{note}</small></article>)}</section>
    <section className="content-grid primary-grid"><article className="panel-card usage-panel" id="usage"><div className="panel-heading"><div><p className="eyebrow-blue">USAGE ANALYTICS / RECENT</p><h2>{formatGB(data.stats.trafficBalanceGB)} remaining</h2></div><span className="panel-meta">{formatPercent(data.stats.usagePercent)} used</span></div><div className="traffic-progress"><span style={{ width: `${Math.min(100, safeNumber(data.stats.usagePercent))}%` }} /></div><div className="traffic-breakdown"><div><span>Used</span><strong>{formatGB(data.stats.trafficUsedGB)}</strong></div><div><span>Total</span><strong>{formatGB(data.stats.trafficTotalGB)}</strong></div><div><span>Remaining</span><strong>{formatGB(data.stats.trafficBalanceGB)}</strong></div></div><div className="usage-chart">{usageSeries.length ? usageSeries.map((item, index) => <div className="bar-wrap" key={item.id}><div className="usage-bar" style={{ height: `${Math.max(10, Math.min(100, (safeNumber(item.trafficUsedGB) / Math.max(0.01, safeNumber(data.stats.trafficUsedGB))) * 100))}%` }} title={`${item.source}: ${formatGB(item.trafficUsedGB)}`} /><span>{index + 1}</span></div>) : <div className="empty-inline"><ChartBarIcon /><span>No usage data yet.</span></div>}</div>{usageSeries.length > 0 && <div className="usage-list">{usageSeries.slice(0, 3).map((item) => <div key={item.id}><span>{item.source}<small>{new Date(item.recordedAt).toLocaleString()}</small></span><strong>{formatGB(item.trafficUsedGB)}</strong></div>)}</div>}</article>
      <article className="panel-card network-overview"><div className="panel-heading"><div><p className="eyebrow-blue">NETWORK OVERVIEW</p><h2>{providerConnected ? "Providers online" : "No proxy providers connected"}</h2></div><span className="secure-badge"><ShieldCheckIcon /> Control plane ready</span></div><p className="network-overview-copy">{providerConnected ? "Provider inventory is available through the VornShield gateway." : "Your VornShield gateway is ready. Connect a provider to begin provisioning proxy infrastructure."}</p><div className="network-flow"><div><span className="network-node gateway-node"><SignalIcon /></span><strong>Gateway</strong><small>Operational</small></div><i /><div><span className="network-node"><CubeIcon /></span><strong>Provider layer</strong><small>{providerConnected ? "Available" : "Not connected"}</small></div><i /><div><span className="network-node"><ChartBarIcon /></span><strong>Traffic</strong><small>{formatGB(data.stats.trafficUsedGB)} used</small></div></div><div className="network-note"><LockClosedIcon /> Provider locations, sessions and endpoint health remain unavailable until real inventory is connected.</div><Link href="/proxies" className="primary-button full">View providers <ArrowRightOnRectangleIcon /></Link></article></section>
    <section className="content-grid secondary-grid"><article className="panel-card" id="credentials"><div className="panel-heading"><div><p className="eyebrow-blue">PROXY ACCESS</p><h2>Credentials</h2></div><span className="secure-badge"><ShieldCheckIcon /> Secure</span></div><div className="credentials-list"><CopyCredential label="HTTP" value={`${data.httpProxy.username}@${data.httpProxy.host}:${data.httpProxy.port}`} /><CopyCredential label="SOCKS5" value={`${data.socks5Proxy.username}@${data.socks5Proxy.host}:${data.socks5Proxy.port}`} /></div></article><article className="panel-card"><div className="panel-heading"><div><p className="eyebrow-blue">BILLING</p><h2>Recent top-ups</h2></div><Link href="/billing" className="text-link">View all</Link></div><div className="payment-list">{payments.length ? payments.slice(0, 4).map((payment) => <div className="payment-row" key={payment.id}><span className="payment-dot"><CreditCardIcon /></span><span><strong>{payment.reference}</strong><small>{payment.status} · {new Date(payment.createdAt).toLocaleDateString()}</small></span><b>{money(payment.amountMinorUnits, payment.currency)}</b></div>) : <div className="empty-inline compact"><CreditCardIcon /><span>No recent payments.</span></div>}</div></article></section>
    <section className="panel-card plans-panel"><div className="panel-heading"><div><p className="eyebrow-blue">AVAILABLE TRAFFIC</p><h2>Choose proxy traffic</h2></div><Link href="/billing" className="text-link">Open billing <ArrowRightOnRectangleIcon /></Link></div><div className="plan-grid">{plans.length ? plans.slice(0, 3).map((plan) => <div className={`plan-card ${plan.isPopular ? "popular" : ""}`} key={plan.id}>{plan.isPopular && <span className="popular-label">POPULAR</span>}<span className="plan-name">{plan.name}</span><strong>{money(plan.priceMinorUnits, plan.currency)}</strong><span className="plan-credits">{formatGB(plan.trafficGB)}</span><p>{plan.description}</p><Link href="/billing" className="plan-link">Select plan <ArrowRightOnRectangleIcon /></Link></div>) : <div className="empty-inline compact"><CubeIcon /><span>No plans available.</span></div>}</div></section>
    {data.user.role === "admin" && <section className="admin-sync"><div><p className="eyebrow-blue">ADMIN TOOL</p><strong>Proxy daemon configuration</strong><small>Sync active users to the running proxy configuration.</small></div><button className="secondary-button" onClick={() => void onSyncProxy()} disabled={syncingProxy}><ArrowPathIcon className={syncingProxy ? "spin" : ""} />{syncingProxy ? "Syncing" : "Sync daemons"}</button>{syncResult && <span className="sync-success">{syncResult.userCount} users synced</span>}</section>}
  </div></AppShell>;
}
